#!/bin/bash

# ------------------------------------------------------------------------------------------------------------------------------------------------------------
# BACKUP PURGE SCRIPT
# ------------------------------------------------------------------------------------------------------------------------------------------------------------
#
# @author Aufrère Guillian
# @copyright 2022
#

# ------------------------------------------------------------------------------------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------------------------------------------------------------------------------------

# The directory to purge.
PURGE_DIRECTORY="/mnt/remotes/ANTONIN.IP_guillian_backups"

# The pattern to find files to purge.
# /!\ Pay attention to this pattern !
PATTERN="*.tar.gz.age"

# Number of days backups should be kept.
# All files with pattern is matching > to DAYS_RETENTION value will be removed.
DAYS_RETENTION=3

# ------------------------------------------------------------------------------------------------------------------------------------------------------------
# SCRIPT COLORS
# ------------------------------------------------------------------------------------------------------------------------------------------------------------
NC='\033[0m'    # Text Reset

# Regular             Bold                  Underline             High Intensity        BoldHigh Intens       Background            High Intensity Backgrounds
Bla='\033[0;30m';     BBla='\033[1;30m';    UBla='\033[4;30m';    IBla='\033[0;90m';    BIBla='\033[1;90m';   On_Bla='\033[40m';    On_IBla='\033[0;100m';
Red='\033[0;31m';     BRed='\033[1;31m';    URed='\033[4;31m';    IRed='\033[0;91m';    BIRed='\033[1;91m';   On_Red='\033[41m';    On_IRed='\033[0;101m';
Gre='\033[0;32m';     BGre='\033[1;32m';    UGre='\033[4;32m';    IGre='\033[0;92m';    BIGre='\033[1;92m';   On_Gre='\033[42m';    On_IGre='\033[0;102m';
Yel='\033[0;33m';     BYel='\033[1;33m';    UYel='\033[4;33m';    IYel='\033[0;93m';    BIYel='\033[1;93m';   On_Yel='\033[43m';    On_IYel='\033[0;103m';
Blu='\033[0;34m';     BBlu='\033[1;34m';    UBlu='\033[4;34m';    IBlu='\033[0;94m';    BIBlu='\033[1;94m';   On_Blu='\033[44m';    On_IBlu='\033[0;104m';
Pur='\033[0;35m';     BPur='\033[1;35m';    UPur='\033[4;35m';    IPur='\033[0;95m';    BIPur='\033[1;95m';   On_Pur='\033[45m';    On_IPur='\033[0;105m';
Cya='\033[0;36m';     BCya='\033[1;36m';    UCya='\033[4;36m';    ICya='\033[0;96m';    BICya='\033[1;96m';   On_Cya='\033[46m';    On_ICya='\033[0;106m';
Whi='\033[0;37m';     BWhi='\033[1;37m';    UWhi='\033[4;37m';    IWhi='\033[0;97m';    BIWhi='\033[1;97m';   On_Whi='\033[47m';    On_IWhi='\033[0;107m';

# ------------------------------------------------------------------------------------------------------------------------------------------------------------
# CONSOLE FUNCTIONS
# ------------------------------------------------------------------------------------------------------------------------------------------------------------
bigTitle()
{
    echo -e "$(date +'%Y-%m-%d') ${BIBlu}#--------------------------------------------------------------#${NC}"
    echo -e "$(date +'%Y-%m-%d') ${BIBlu}# $1${NC}"
    echo -e "$(date +'%Y-%m-%d') ${BIBlu}#--------------------------------------------------------------#${NC}"
}

title()
{
    echo -e "$(date +'%Y-%m-%d') ${Blu}----------------------------------------------------------------${NC}"
    echo -e "$(date +'%Y-%m-%d') ${Blu}$1${NC}"
    echo -e "$(date +'%Y-%m-%d') ${Blu}----------------------------------------------------------------${NC}"
}

section()
{
    echo -e "$(date +'%Y-%m-%d') ${Cya}# --- $1 ${NC}"
}

info()
{
    echo -e "$(date +'%Y-%m-%d') ${Cya}INFO${NC} $1"
}

success()
{
    echo -e "$(date +'%Y-%m-%d') ${Gre}SUCCESS${NC} $1."
}

error()
{
    echo -e "$(date +'%Y-%m-%d') ${Red}ERROR${NC} $1."
}

# ------------------------------------------------------------------------------------------------------------------------------------------------------------
# SCRIPT ITSELF
# ------------------------------------------------------------------------------------------------------------------------------------------------------------
bigTitle "BACKUP PURGE SCRIPT START"

if [ ! -d "$PURGE_DIRECTORY" ]
then
    error "Backup directory not found."
    info "${Yel}$PURGE_DIRECTORY{NC}"
    exit
fi

success "Backup directory found."
info "${Yel}$PURGE_DIRECTORY{NC}"

section "Find files to purge."
find ${PURGE_DIRECTORY} -name ${PATTERN} -mtime +${DAYS_RETENTION}

section "Purge files.."
find ${PURGE_DIRECTORY} -name ${PATTERN} -mtime +${DAYS_RETENTION} -delete

success "Purge ended"